# Generated by Django 6.0 on 2025-12-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cosign", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="pfp_url",
        ),
    ]
