# Generated by Django 6.0 on 2025-12-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosign", "0002_remove_profile_pfp_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.TextField(blank=True),
        ),
    ]
