# Generated by Django 6.0 on 2026-01-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosign", "0003_rename_name_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="pfp_file",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
