# Generated by Django 6.0 on 2026-01-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosign', '0004_alter_profile_pfp_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp_file',
            field=models.ImageField(blank=True, default='defaultpfp.jpg', null=True, upload_to=''),
        ),
    ]
