# Generated by Django 6.0 on 2026-01-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosign", "0005_alter_profile_pfp_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="pfp_file",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
